clc; clear all; close all;

% Select some maneuver to test %
load("data/flight_data/selected_data/fpr_data_lon.mat");
load("data/flight_data/selected_data/fpr_data_lat.mat");

maneuvers = {fpr_data_lon.validation.pitch_211(1) ...
    fpr_data_lon.validation.pitch_211(2) ...
    fpr_data_lat.validation.roll_211(1) ...
    fpr_data_lat.validation.roll_211(2) ...
    fpr_data_lat.validation.yaw_211(1) ...
    fpr_data_lat.validation.yaw_211(2)};

filenames = ["pitch_maneuver_input.csv" ...
    "pitch_maneuver_2_input.csv" ...
    "roll_maneuver_right_input.csv" ...
    "roll_maneuver_left_input.csv" ...
    "yaw_maneuver_right_input.csv" ...
    "yaw_maneuver_left_input.csv"];

output_location = "data/recorded_example_inputs/";

for maneuver_i = 1:length(maneuvers)
    maneuver = maneuvers{maneuver_i};
    N = length(maneuver.Time);
    inputs = [...
        maneuver.DeltaASpAbsolute maneuver.DeltaESpAbsolute maneuver.DeltaRSp maneuver.DeltaT ...
        zeros(N,1) zeros(N,1) zeros(N,1) zeros(N,1)];
    writematrix(inputs,output_location + filenames(maneuver_i));
end