vehicle_cmd_trans = {
    "0": "VEHICLE_CMD_CUSTOM_0",  # test command
    "1": "VEHICLE_CMD_CUSTOM_1",  # test command
    "2": "VEHICLE_CMD_CUSTOM_2",  # test command
    "16": "VEHICLE_CMD_NAV_WAYPOINT",  # Navigate to MISSION. |Hold time in decimal seconds. (ignored by fixed wing, time to stay at MISSION for rotary wing)| Acceptance radius in meters (if the sphere with this radius is hit, the MISSION counts as reached)| 0 to pass through the WP, if > 0 radius in meters to pass by WP. Positive value for clockwise orbit, negative value for counter-clockwise orbit. Allows trajectory control.| Desired yaw angle at MISSION (rotary wing)| Latitude| Longitude| Altitude|
    "17": "VEHICLE_CMD_NAV_LOITER_UNLIM",  # Loiter around this MISSION an unlimited amount of time |Empty| Empty| Radius around MISSION, in meters. If positive loiter clockwise, else counter-clockwise| Desired yaw angle.| Latitude| Longitude| Altitude|
    "18": "VEHICLE_CMD_NAV_LOITER_TURNS",  # Loiter around this MISSION for X turns |Turns| Empty| Radius around MISSION, in meters. If positive loiter clockwise, else counter-clockwise| Desired yaw angle.| Latitude| Longitude| Altitude|
    "19": "VEHICLE_CMD_NAV_LOITER_TIME",  # Loiter around this MISSION for X seconds |Seconds (decimal)| Empty| Radius around MISSION, in meters. If positive loiter clockwise, else counter-clockwise| Desired yaw angle.| Latitude| Longitude| Altitude|
    "20": "VEHICLE_CMD_NAV_RETURN_TO_LAUNCH",  # Return to launch location |Empty| Empty| Empty| Empty| Empty| Empty| Empty|
    "21": "VEHICLE_CMD_NAV_LAND",  # Land at location |Empty| Empty| Empty| Desired yaw angle.| Latitude| Longitude| Altitude|
    "22": "VEHICLE_CMD_NAV_TAKEOFF",  # Takeoff from ground / hand |Minimum pitch (if airspeed sensor present), desired pitch without sensor| Empty| Empty| Yaw angle (if magnetometer present), ignored without magnetometer| Latitude| Longitude| Altitude|
    "23": "VEHICLE_CMD_NAV_PRECLAND",  # Attempt a precision landing
    "34": "VEHICLE_CMD_DO_ORBIT",  # Start orbiting on the circumference of a circle defined by the parameters. |Radius [m] |Velocity [m/s] |Yaw behaviour |Empty |Latitude/X |Longitude/Y |Altitude/Z |
    "80": "VEHICLE_CMD_NAV_ROI",  # Sets the region of interest (ROI) for a sensor set or the vehicle itself. This can then be used by the vehicles control system to control the vehicle attitude and the attitude of various sensors such as cameras. |Region of interest mode. (see MAV_ROI enum)| MISSION index/ target ID. (see MAV_ROI enum)| ROI index (allows a vehicle to manage multiple ROI's)| Empty| x the location of the fixed ROI (see MAV_FRAME)| y| z|
    "81": "VEHICLE_CMD_NAV_PATHPLANNING",  # Control autonomous path planning on the MAV. |0: Disable local obstacle avoidance / local path planning (without resetting map), 1: Enable local path planning, 2: Enable and reset local path planning| 0: Disable full path planning (without resetting map), 1: Enable, 2: Enable and reset map/occupancy grid, 3: Enable and reset planned route, but not occupancy grid| Empty| Yaw angle at goal, in compass degrees, [0..360]| Latitude/X of goal| Longitude/Y of goal| Altitude/Z of goal|
    "84": "VEHICLE_CMD_NAV_VTOL_TAKEOFF",  # Takeoff from ground / hand and transition to fixed wing |Minimum pitch (if airspeed sensor present), desired pitch without sensor| Empty| Empty| Yaw angle (if magnetometer present), ignored without magnetometer| Latitude| Longitude| Altitude|
    "85": "VEHICLE_CMD_NAV_VTOL_LAND",  # Transition to MC and land at location |Empty| Empty| Empty| Desired yaw angle.| Latitude| Longitude| Altitude|
    "90": "VEHICLE_CMD_NAV_GUIDED_LIMITS",  # set limits for external control |timeout - maximum time (in seconds) that external controller will be allowed to control vehicle. 0 means no timeout| absolute altitude min (in meters, AMSL) - if vehicle moves below this alt, the command will be aborted and the mission will continue.  0 means no lower altitude limit| absolute altitude max (in meters)- if vehicle moves above this alt, the command will be aborted and the mission will continue.  0 means no upper altitude limit| horizontal move limit (in meters, AMSL) - if vehicle moves more than this distance from it's location at the moment the command was executed, the command will be aborted and the mission will continue. 0 means no horizontal altitude limit| Empty| Empty| Empty|
    "91": "VEHICLE_CMD_NAV_GUIDED_MASTER",  # set id of master controller |System ID| Component ID| Empty| Empty| Empty| Empty| Empty|
    "92": "VEHICLE_CMD_NAV_GUIDED_ENABLE",  # hand control over to an external controller |On / Off (> 0.5f on)| Empty| Empty| Empty| Empty| Empty| Empty|
    "93": "VEHICLE_CMD_NAV_DELAY",  # Delay the next navigation command a number of seconds or until a specified time |Delay in seconds (decimal, -1 to enable time-of-day fields)| hour (24h format, UTC, -1 to ignore)| minute (24h format, UTC, -1 to ignore)| second (24h format, UTC)| Empty| Empty| Empty|
    "95": "VEHICLE_CMD_NAV_LAST",  # NOP - This command is only used to mark the upper limit of the NAV/ACTION commands in the enumeration |Empty| Empty| Empty| Empty| Empty| Empty| Empty|
    "112": "VEHICLE_CMD_CONDITION_DELAY",  # Delay mission state machine. |Delay in seconds (decimal)| Empty| Empty| Empty| Empty| Empty| Empty|
    "113": "VEHICLE_CMD_CONDITION_CHANGE_ALT",  # Ascend/descend at rate.  Delay mission state machine until desired altitude reached. |Descent / Ascend rate (m/s)| Empty| Empty| Empty| Empty| Empty| Finish Altitude|
    "114": "VEHICLE_CMD_CONDITION_DISTANCE",  # Delay mission state machine until within desired distance of next NAV point. |Distance (meters)| Empty| Empty| Empty| Empty| Empty| Empty|
    "115": "VEHICLE_CMD_CONDITION_YAW",  # Reach a certain target angle. |target angle: [0-360], 0 is north| speed during yaw change:[deg per second]| direction: negative: counter clockwise, positive: clockwise [-1,1]| relative offset or absolute angle: [ 1,0]| Empty| Empty| Empty|
    "159": "VEHICLE_CMD_CONDITION_LAST",  # NOP - This command is only used to mark the upper limit of the CONDITION commands in the enumeration |Empty| Empty| Empty| Empty| Empty| Empty| Empty|
    "4501": "VEHICLE_CMD_CONDITION_GATE",  # Wait until passing a threshold |2D coord mode: 0: Orthogonal to planned route | Altitude mode: 0: Ignore altitude| Empty| Empty| Lat| Lon| Alt|
    "176": "VEHICLE_CMD_DO_SET_MODE",  # Set system mode. |Mode, as defined by ENUM MAV_MODE| Empty| Empty| Empty| Empty| Empty| Empty|
    "177": "VEHICLE_CMD_DO_JUMP",  # Jump to the desired command in the mission list.  Repeat this action only the specified number of times |Sequence number| Repeat count| Empty| Empty| Empty| Empty| Empty|
    "178": "VEHICLE_CMD_DO_CHANGE_SPEED",  # Change speed and/or throttle set points. |Speed type (0=Airspeed, 1=Ground Speed)| Speed  (m/s, -1 indicates no change)| Throttle  ( Percent, -1 indicates no change)| Empty| Empty| Empty| Empty|
    "179": "VEHICLE_CMD_DO_SET_HOME",  # Changes the home location either to the current location or a specified location. |Use current (1=use current location, 0=use specified location)| Empty| Empty| Empty| Latitude| Longitude| Altitude|
    "180": "VEHICLE_CMD_DO_SET_PARAMETER",  # Set a system parameter.  Caution!  Use of this command requires knowledge of the numeric enumeration value of the parameter. |Parameter number| Parameter value| Empty| Empty| Empty| Empty| Empty|
    "181": "VEHICLE_CMD_DO_SET_RELAY",  # Set a relay to a condition. |Relay number| Setting (1=on, 0=off, others possible depending on system hardware)| Empty| Empty| Empty| Empty| Empty|
    "182": "VEHICLE_CMD_DO_REPEAT_RELAY",  # Cycle a relay on and off for a desired number of cyles with a desired period. |Relay number| Cycle count| Cycle time (seconds, decimal)| Empty| Empty| Empty| Empty|
    "183": "VEHICLE_CMD_DO_SET_SERVO",  # Set a servo to a desired PWM value. |Servo number| PWM (microseconds, 1000 to 2000 typical)| Empty| Empty| Empty| Empty| Empty|
    "184": "VEHICLE_CMD_DO_REPEAT_SERVO",  # Cycle a between its nominal setting and a desired PWM for a desired number of cycles with a desired period. |Servo number| PWM (microseconds, 1000 to 2000 typical)| Cycle count| Cycle time (seconds)| Empty| Empty| Empty|
    "185": "VEHICLE_CMD_DO_FLIGHTTERMINATION",  # Terminate flight immediately |Flight termination activated if > 0.5| Empty| Empty| Empty| Empty| Empty| Empty|
    "189": "VEHICLE_CMD_DO_LAND_START",  # Mission command to perform a landing. This is used as a marker in a mission to tell the autopilot where a sequence of mission items that represents a landing starts. It may also be sent via a COMMAND_LONG to trigger a landing, in which case the nearest (geographically) landing sequence in the mission will be used. The Latitude/Longitude is optional, and may be set to 0/0 if not needed. If specified then it will be used to help find the closest landing sequence. |Empty| Empty| Empty| Empty| Latitude| Longitude| Empty|  */
    "191": "VEHICLE_CMD_DO_GO_AROUND",  # Mission command to safely abort an autonmous landing. |Altitude (meters)| Empty| Empty| Empty| Empty| Empty| Empty|  */
    "192": "VEHICLE_CMD_DO_REPOSITION",
    "193": "VEHICLE_CMD_DO_PAUSE_CONTINUE ",
    "195": "VEHICLE_CMD_DO_SET_ROI_LOCATION",  # Sets the region of interest (ROI) to a location. This can then be used by the vehicles control system to control the vehicle attitude and the attitude of various sensors such as cameras. |Empty| Empty| Empty| Empty| Latitude| Longitude| Altitude|
    "196": "VEHICLE_CMD_DO_SET_ROI_WPNEXT_OFFSET",  # Sets the region of interest (ROI) to be toward next waypoint, with optional pitch/roll/yaw offset. This can then be used by the vehicles control system to control the vehicle attitude and the attitude of various sensors such as cameras. |Empty| Empty| Empty| Empty| pitch offset from next waypoint| roll offset from next waypoint| yaw offset from next waypoint|
    "197": "VEHICLE_CMD_DO_SET_ROI_NONE",  # Cancels any previous ROI command returning the vehicle/sensors to default flight characteristics. This can then be used by the vehicles control system to control the vehicle attitude and the attitude of various sensors such as cameras. |Empty| Empty| Empty| Empty| Empty| Empty| Empty|
    "200": "VEHICLE_CMD_DO_CONTROL_VIDEO",  # Control onboard camera system. |Camera ID (-1 for all)| Transmission: 0: disabled, 1: enabled compressed, 2: enabled raw| Transmission mode: 0: video stream, >0: single images every n seconds (decimal)| Recording: 0: disabled, 1: enabled compressed, 2: enabled raw| Empty| Empty| Empty|
    "201": "VEHICLE_CMD_DO_SET_ROI",  # Sets the region of interest (ROI) for a sensor set or the vehicle itself. This can then be used by the vehicles control system to control the vehicle attitude and the attitude of various sensors such as cameras. |Region of interest mode. (see MAV_ROI enum)| MISSION index/ target ID. (see MAV_ROI enum)| ROI index (allows a vehicle to manage multiple ROI's)| Empty| x the location of the fixed ROI (see MAV_FRAME)| y| z|
    "203": "VEHICLE_CMD_DO_DIGICAM_CONTROL",
    "204": "VEHICLE_CMD_DO_MOUNT_CONFIGURE",  # Mission command to configure a camera or antenna mount |Mount operation mode (see MAV_MOUNT_MODE enum)| stabilize roll? (1 = yes, 0 = no)| stabilize pitch? (1 = yes, 0 = no)| stabilize yaw? (1 = yes, 0 = no)| Empty| Empty| Empty|
    "205": "VEHICLE_CMD_DO_MOUNT_CONTROL",  # Mission command to control a camera or antenna mount |pitch or lat in degrees, depending on mount mode.| roll or lon in degrees depending on mount mode| yaw or alt (in meters) depending on mount mode| reserved| reserved| reserved| MAV_MOUNT_MODE enum value|
    "206": "VEHICLE_CMD_DO_SET_CAM_TRIGG_DIST",  # Mission command to set TRIG_DIST for this flight |Camera trigger distance (meters)| Shutter integration time (ms)| Empty| Empty| Empty| Empty| Empty|
    "207": "VEHICLE_CMD_DO_FENCE_ENABLE",  # Mission command to enable the geofence |enable? (0=disable, 1=enable)| Empty| Empty| Empty| Empty| Empty| Empty|
    "208": "VEHICLE_CMD_DO_PARACHUTE",  # Mission command to trigger a parachute |action (0=disable, 1=enable, 2=release, for some systems see PARACHUTE_ACTION enum, not in general message set.)| Empty| Empty| Empty| Empty| Empty| Empty|
    "209": "VEHICLE_CMD_DO_MOTOR_TEST",  # motor test command |Instance (1, ...)| throttle type| throttle| timeout [s]| Motor count | Test order| Empty|
    "210": "VEHICLE_CMD_DO_INVERTED_FLIGHT",  # Change to/from inverted flight |inverted (0=normal, 1=inverted)| Empty| Empty| Empty| Empty| Empty| Empty|
    "214": "VEHICLE_CMD_DO_SET_CAM_TRIGG_INTERVAL",  # Mission command to set TRIG_INTERVAL for this flight |Camera trigger distance (meters)| Shutter integration time (ms)| Empty| Empty| Empty| Empty| Empty|
    "220": "VEHICLE_CMD_DO_MOUNT_CONTROL_QUAT",  # Mission command to control a camera or antenna mount, using a quaternion as reference. |q1 - quaternion param #1, w (1 in null-rotation)| q2 - quaternion param #2, x (0 in null-rotation)| q3 - quaternion param #3, y (0 in null-rotation)| q4 - quaternion param #4, z (0 in null-rotation)| Empty| Empty| Empty|
    "221": "VEHICLE_CMD_DO_GUIDED_MASTER",  # set id of master controller |System ID| Component ID| Empty| Empty| Empty| Empty| Empty|
    "222": "VEHICLE_CMD_DO_GUIDED_LIMITS",  # set limits for external control |timeout - maximum time (in seconds) that external controller will be allowed to control vehicle. 0 means no timeout| absolute altitude min (in meters, AMSL) - if vehicle moves below this alt, the command will be aborted and the mission will continue.  0 means no lower altitude limit| absolute altitude max (in meters)- if vehicle moves above this alt, the command will be aborted and the mission will continue.  0 means no upper altitude limit| horizontal move limit (in meters, AMSL) - if vehicle moves more than this distance from it's location at the moment the command was executed, the command will be aborted and the mission will continue. 0 means no horizontal altitude limit| Empty| Empty| Empty|
    "240": "VEHICLE_CMD_DO_LAST",  # NOP - This command is only used to mark the upper limit of the DO commands in the enumeration |Empty| Empty| Empty| Empty| Empty| Empty| Empty|
    "241": "VEHICLE_CMD_PREFLIGHT_CALIBRATION",  # Trigger calibration. This command will be only accepted if in pre-flight mode. See mavlink spec MAV_CMD_PREFLIGHT_CALIBRATION
    "3": "PREFLIGHT_CALIBRATION_TEMPERATURE_CALIBRATION",  # param value for VEHICLE_CMD_PREFLIGHT_CALIBRATION to start temperature calibration
    "242": "VEHICLE_CMD_PREFLIGHT_SET_SENSOR_OFFSETS",  # Set sensor offsets. This command will be only accepted if in pre-flight mode. |Sensor to adjust the offsets for: 0: gyros, 1: accelerometer, 2: magnetometer, 3: barometer, 4: optical flow| X axis offset (or generic dimension 1), in the sensor's raw units| Y axis offset (or generic dimension 2), in the sensor's raw units| Z axis offset (or generic dimension 3), in the sensor's raw units| Generic dimension 4, in the sensor's raw units| Generic dimension 5, in the sensor's raw units| Generic dimension 6, in the sensor's raw units|
    "243": "VEHICLE_CMD_PREFLIGHT_UAVCAN",  # UAVCAN configuration. If param 1 == 1 actuator mapping and direction assignment should be started
    "245": "VEHICLE_CMD_PREFLIGHT_STORAGE",  # Request storage of different parameter values and logs. This command will be only accepted if in pre-flight mode. |Parameter storage: 0: READ FROM FLASH/EEPROM, 1: WRITE CURRENT TO FLASH/EEPROM| Mission storage: 0: READ FROM FLASH/EEPROM, 1: WRITE CURRENT TO FLASH/EEPROM| Reserved| Reserved| Empty| Empty| Empty|
    "246": "VEHICLE_CMD_PREFLIGHT_REBOOT_SHUTDOWN",  # Request the reboot or shutdown of system components. |0: Do nothing for autopilot, 1: Reboot autopilot, 2: Shutdown autopilot.| 0: Do nothing for onboard computer, 1: Reboot onboard computer, 2: Shutdown onboard computer.| Reserved| Reserved| Empty| Empty| Empty|
    "260": "VEHICLE_CMD_OBLIQUE_SURVEY",  # Mission command to set a Camera Auto Mount Pivoting Oblique Survey for this flight|Camera trigger distance (meters)| Shutter integration time (ms)| Camera minimum trigger interval| Number of positions| Roll| Pitch| Empty|
    "300": "VEHICLE_CMD_MISSION_START",  # start running a mission |first_item: the first mission item to run| last_item:  the last mission item to run (after this item is run, the mission ends)|
    "400": "VEHICLE_CMD_COMPONENT_ARM_DISARM",  # Arms / Disarms a component |1 to arm, 0 to disarm|
    "420": "VEHICLE_CMD_INJECT_FAILURE",  # Inject artificial failure for testing purposes
    "500": "VEHICLE_CMD_START_RX_PAIR",  # Starts receiver pairing |0:Spektrum| 0:Spektrum DSM2, 1:Spektrum DSMX|
    "530": "VEHICLE_CMD_SET_CAMERA_MODE",  # Set camera capture mode (photo, video, etc.)
    "531": "VEHICLE_CMD_SET_CAMERA_ZOOM",  # Set camera zoom
    "2003": "VEHICLE_CMD_DO_TRIGGER_CONTROL",  # Enable or disable on-board camera triggering system
    "2510": "VEHICLE_CMD_LOGGING_START",  # start streaming ULog data
    "2511": "VEHICLE_CMD_LOGGING_STOP",  # stop streaming ULog data
    "2600": "VEHICLE_CMD_CONTROL_HIGH_LATENCY",  # control starting/stopping transmitting data over the high latency link
    "3000": "VEHICLE_CMD_DO_VTOL_TRANSITION",  # Command VTOL transition
    "3001": "VEHICLE_CMD_ARM_AUTHORIZATION_REQUEST",  # Request arm authorization
    "30001": "VEHICLE_CMD_PAYLOAD_PREPARE_DEPLOY",  # Prepare a payload deployment in the flight plan
    "30002": "VEHICLE_CMD_PAYLOAD_CONTROL_DEPLOY",  # Control a pre-programmed payload deployment
    "42006": "VEHICLE_CMD_FIXED_MAG_CAL_YAW",  # Magnetometer calibration based on provided known yaw. This allows for fast calibration using WMM field tables in the vehicle, given only the known yaw of the vehicle. If Latitude and longitude are both zero then use the current vehicle location.
}
