function [u, v, w] = calc_body_vel(phi, theta, psi, v_N, v_E, v_D)
    u = cos(theta) .* cos(psi) .* v_N + cos(theta) .* sin(psi) .* v_E - sin(theta) .* v_D;
    v = (cos(psi) .* sin(theta) .* sin(phi) - cos(phi) .* sin(psi)) .* v_N ...
        + (cos(phi) .* cos(psi) + sin(theta) .* sin(phi) .* sin(psi)) .* v_E ...
        + cos(theta) .* sin(phi) .* v_D;
    w = (cos(psi) .* sin(theta) .* cos(phi) + sin(phi) .* sin(psi)) .* v_N ...
        + (sin(theta) .* cos(phi) .* sin(psi) - sin(phi) .* cos(psi)) .* v_E ...
        + cos(theta) .* cos(phi) .* v_D;
end